# Generated by Django 5.0.3 on 2024-03-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='civil_status',
            field=models.CharField(choices=[('CA', 'Casad@'), ('DI', 'Divorciad@'), ('VI', 'Viud@'), ('UL', 'Union libre')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='', max_length=100, verbose_name='Sexo'),
        ),
    ]
