# Generated by Django 5.0.3 on 2024-03-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_civil_status_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='civil_status',
            field=models.CharField(choices=[('', ''), ('CA', 'Casad@'), ('DI', 'Divorciad@'), ('VI', 'Viud@'), ('UL', 'Union libre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('', ''), ('F', 'Femenino'), ('M', 'Masculino')], max_length=100, verbose_name='Sexo'),
        ),
    ]
